---
- name: Create storage bucket. Ignore error if bucket already exists.
  shell: gsutil mb -p {{gce_project}} gs://{{google_storage_bucket}}/
  ignore_errors: yes
  when: "storage_type == 'google_storage'"
