- name: Delete the MySQL database container
  docker_container:
    name: "{{ mysql_container_name }}"
    state: absent

- name: Delete the rabbitmq container
  docker_container:
    name: "{{ rabbitmq_container_name }}"
    state: absent

- name: Delete the container with celery workers
  docker_container:
    name: "{{ worker_container_name }}"
    state: absent

- name: Delete the container with celery scheduler
  docker_container:
    name: "{{ scheduler_container_name }}"
    state: absent

- name: Delete the container with flower
  docker_container:
    name: "{{ flower_container_name }}"
    state: absent

- name: Delete the container with the Loom Master webserver
  docker_container:
    name: "{{ master_container_name }}"
    state: absent

- name: Delete the NGINX server container
  docker_container:
    name: "{{ nginx_container_name }}"
    state: absent

- name: Delete the Fluentd server container
  docker_container:
    name: "{{ fluentd_container_name }}"
    state: absent
